version: "3.5"

services:
  mongodb:
    image: mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend


volumes:
  mongodata:

networks:
  backend: